#!/bin/sh

# config
region=Moscow,ru
units=metric  # internal, metric, imperial
sleep_time=22:00
wake_up_time=06:00
blink1_tool_args=
# end config

prog=$(basename "$0")
# http://openweathermap.org/forecast
url="http://api.openweathermap.org/data/2.5/forecast/daily?q=${region}&mode=json&units=${units}&cnt=1"
state_file=/tmp/blink1-weather.state

blink1_tool() {
    blink1-tool $blink1_tool_args "$@" >/dev/null
    rc=$?

    if [ "$rc" != 0 ]; then
        echo "$prog: blink1-tool dies with code $rc" >&2
        rm -f "$state_file"
        exit 1
    fi
}

if [ "$(date +%H%M)" -lt "$(echo "$wake_up_time" | tr -d :)" ]; then
    rm -f "$state_file"
    blink1_tool --off
    exit 0
fi

if [ "$(date +%H%M)" -ge "$(echo "$sleep_time" | tr -d :)" ]; then
    rm -f "$state_file"
    blink1_tool --off
    exit 0
fi

weather_id=$(wget -q -O - "$url" | jq '.list[0].weather[0].id')

if [ -z "$weather_id" ]; then
    echo "$prog: cannot get weather id" >&2
    exit 1
fi

state=0
mode=off
rgb=0,0,0
fading=300
delay=500

# http://openweathermap.org/weather-conditions
case $weather_id in
    2??)  # thunderstorm
        state=2
        mode=blink
        rgb=192,0,192
    ;;
    3??)  # drizzle
        state=3
        mode=on
        rgb=0,0,128
    ;;
    5??)  # rain
        state=5
        mode=blink
        rgb=0,0,192
        fading=500
        delay=2000
    ;;
    6??)  # snow
    ;;
    7??)  # atmosphere
    ;;
    8??)  # clouds
    ;;
    90?)  # extreme
        state=9.1
        mode=blink
        rgb=255,0,0
    ;;
    950|951|952|953|954|955|956)  # additional, setting - strong breeze
    ;;
    957|958|959|960|961|962)  # additional, high wind - hurricane
        state=9.2
        mode=blink
        rgb=255,0,0
    ;;
    *)
        echo "$prog: unknown weather id: $weather_id" >&2
        rm -f "$state_file"
        blink1_tool --off
        exit 1
    ;;
esac

if [ -r "$state_file" ]; then
    prev_state=$(cat "$state_file")
fi

if [ "$prev_state" != "$state" ]; then
    echo "$state" >"$state_file"
    chmod 0666 "$state_file"
fi

case $mode in
  blink)
        if [ "$prev_state" = "$state" ]; then
            blink1-tool $blink1_tool_args --playstate \
                | grep -qF playing:1 && exit 0
        fi

        blink1_tool --off
        blink1_tool --rgb "$rgb" --millis "$fading"             --setpattline 0
        blink1_tool --rgb "$rgb" --millis "$((delay - fading))" --setpattline 1
        blink1_tool --rgb 0,0,0  --millis "$fading"             --setpattline 2
        blink1_tool --rgb 0,0,0  --millis "$((delay - fading))" --setpattline 3
        blink1_tool --play 1,0,3,0
    ;;
    on)
        blink1_tool --rgb "$rgb"
    ;;
    *)
        blink1_tool --off
    ;;
esac
